- hosts: localhost
  become: true

  tasks:
    - name: Install squid and htpasswd generator with apt
      apt:
        state: present
        update_cache: yes
        autoclean: yes
        force_apt_get: yes
        cache_valid_time: 3600
        name:
          - squid
          - python3-passlib
          - apache2-utils

    - name: Check if config file exists at standard location
      stat:
        path: /etc/squid/squid.conf
      register: stat_result

    - name: Create htpasswd with standard login
      ansible.builtin.command: htpasswd -bc /etc/squid/squid.htpasswd dmiproxy {{ DMIPROXY_PASSWORD|quote }}

    - name: Set ownership and chmod for htpasswd file
      file: 
        path: /etc/squid/squid.htpasswd
        owner: root
        group: root
        mode: 0640

    - name: Overwrite with default config
      ansible.builtin.copy:
          force: yes
          src: files/etc/squid.conf
          dest: /etc/squid/squid.conf
          owner: root
          group: root

    - name: Restart squid service
      service:
        name: squid
        state: restarted
